### PR TITLE
JENKINS-32197

### PR DESCRIPTION
**Pull request by pmv**
Update filter exclusions and add unit tests.

FYI - these are the changes I'm testing with for now.  Feel free to take or replace with your own changes.

### CODE REVIEW

**Comment by FarmGeek4Life** [comment]
Similar to what you said about git/subversion and NotifyCommit - I don't think that NotifyCommit can directly be used in place of /git or /subversion. I think both will need to exist.

One thought I had before to provide a stopgap measure for any new ones that came up - allow the Jenkins administrator to add in other paths to not authenticate. Still not sure about the best way to do that safely though.

**Comment by FarmGeek4Life** [comment]
I added a branch called "nonauth" to test an idea I had that simplifies this problem - took me a little time, but I found where Jenkins internally checks to see if a page requires authentication, and was able to tie into it. I would appreciate it if you could test it.

One issue I know it will have is if you do allow anonymous read access, it will take some work to get it to authenticate (like manually adding "/manage" to the URL). It will take other work to fix this issue, but I would prefer to not have to maintain an internal list of all URLs that don't need authentication.

**Comment by FarmGeek4Life** [comment]
So, that test failed.

The current state of the nonauth branch should function as needed; However, I want to request a change in jenkins.model.Jenkins.java to make the portion I need accessible, rather than private/part of a function that doesn't provide the needed functionality.

**Comment by FarmGeek4Life** [comment]
Made changes to the master branch; they incorporate some principles of your code, but change the method of checking for unsecured paths entirely. If they are satisfactory, please let me know.

**Comment by pmv** [comment]
No problem, I can close this pull request.  One thing I previously noticed is that the filter also seemed to catch static content (*.css, *.js, *.png, etc.).  You may want to change it so the filter doesn't run multiple times on one page?  Maybe your changes to master addresses this - I haven't had time to look at them.

I'll try to give better feedback once I get some time to try to run this again, but it might not be real soon.  Thanks.

**Comment by FarmGeek4Life** [comment]
Well, the filter runs for each web request; I have no direct control over that, but the change in master also added some distinct paths that are used for static content that I didn't know about before (/adjunct/... for example).

**Pull request closed without merging**
